### ISSUE TITLE
howto: extending this firmware

### ISSUE THREAD

**Issue by noerw** [SodaqMoja/SodaqOne-UniversalTracker-v2#5]
I am interested in extending this tracker with additional sensors, and a secondary / alternative data output. However the codebase is a tad to big for me to grasp, so here are some questions:

- Where would i register an additional field for transmission? Would an addtional field [here](https://github.com/SodaqMoja/SodaqOne-UniversalTracker-v2/blob/master/SodaqOneTracker_v2/ReportDataRecord.h#L119), which gets populated in [`getGPSFixAndTransmit()`](https://github.com/SodaqMoja/SodaqOne-UniversalTracker-v2/blob/master/SodaqOneTracker_v2/SodaqOneTracker_v2.ino#L980) be enough?

- Does the architecture allow reading out a sensor (+adding a record) without getting a new GPS fix?

- Where could I hook a secondary data transmission/storage (eg. writing to SD card), ideally independent from the LoRa enablement configuration?

**Comment by cyclops1982** [comment]
HI,

As i'm trying to learn the code base myself as well, i'll try to answer your questions. I know this is a super old issue though :)

The device works with a timer, which (based on the settings) will fire of a method. The getGPSFixAndTransmit() is one of the more important once of that.
Look for that resetRtcTimerEvents() in the .ino file and you'll see that it's setting up the timers and referring to the runDefaultFixEvent(), which in turn calls the getGPSFixAndTransmit().

The getGPSFixAndtransmit() code works with the pendingReportDataRecord object which basically is an object that has methods to set data. This allows the code to have multiple methods slowly fill the structure. The transmit() method then transmit it. transmit() also takes care of the cayenne stuff.

**Comment by SodaqMoja** [comment]
Questions like these are best dealt with on our forum at https://forum.sodaq.com/
